-- Schema setup for Vulnerability MCP Context Engineering Demo
USE ROLE ALL_AAI_ARCHITECTS;

CREATE DATABASE IF NOT EXISTS SANDBOX;
CREATE SCHEMA IF NOT EXISTS SANDBOX.GDUMA;

USE DATABASE SANDBOX;
USE SCHEMA GDUMA;
