USE DATABASE SANDBOX;
USE SCHEMA GDUMA;

CREATE TABLE IF NOT EXISTS RAW_NVD_CVES (
    CVE_ID VARCHAR(20) NOT NULL,
    SOURCE_IDENTIFIER VARCHAR(100),
    PUBLISHED_DATE TIMESTAMP_NTZ,
    LAST_MODIFIED_DATE TIMESTAMP_NTZ,
    VULN_STATUS VARCHAR(50),
    DESCRIPTION TEXT,
    CVSS_V31_VECTOR VARCHAR(200),
    CVSS_V31_BASE_SCORE FLOAT,
    CVSS_V31_EXPLOITABILITY_SCORE FLOAT,
    CVSS_V31_IMPACT_SCORE FLOAT,
    CWE_IDS VARCHAR(500),
    CPE_CRITERIA TEXT,
    REFERENCES_JSON VARIANT,
    RAW_JSON VARIANT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CVE_ID)
);

CREATE TABLE IF NOT EXISTS RAW_CISA_KEV (
    CVE_ID VARCHAR(20) NOT NULL,
    VENDOR_PROJECT VARCHAR(200),
    PRODUCT VARCHAR(200),
    VULNERABILITY_NAME TEXT,
    DATE_ADDED DATE,
    SHORT_DESCRIPTION TEXT,
    REQUIRED_ACTION TEXT,
    DUE_DATE DATE,
    KNOWN_RANSOMWARE_CAMPAIGN_USE VARCHAR(20),
    NOTES TEXT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CVE_ID)
);

CREATE TABLE IF NOT EXISTS RAW_EPSS_SCORES (
    CVE_ID VARCHAR(20) NOT NULL,
    EPSS_SCORE FLOAT,
    EPSS_PERCENTILE FLOAT,
    MODEL_VERSION VARCHAR(20),
    SCORE_DATE DATE,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CVE_ID)
);

CREATE TABLE IF NOT EXISTS RAW_CWE_WEAKNESSES (
    CWE_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(500),
    ABSTRACTION VARCHAR(50),
    STATUS VARCHAR(50),
    DESCRIPTION TEXT,
    EXTENDED_DESCRIPTION TEXT,
    RELATED_WEAKNESSES TEXT,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CWE_ID)
);

CREATE TABLE IF NOT EXISTS RAW_ATTACK_TECHNIQUES (
    TECHNIQUE_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(500),
    DESCRIPTION TEXT,
    TACTIC VARCHAR(100),
    PLATFORM VARCHAR(200),
    IS_SUBTECHNIQUE BOOLEAN,
    PARENT_TECHNIQUE_ID VARCHAR(20),
    URL VARCHAR(500),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TECHNIQUE_ID)
);

CREATE TABLE IF NOT EXISTS MAP_CWE_ATTACK (
    CWE_ID VARCHAR(20) NOT NULL,
    TECHNIQUE_ID VARCHAR(20) NOT NULL,
    TECHNIQUE_NAME VARCHAR(500),
    TACTIC VARCHAR(100),
    MAPPING_SOURCE VARCHAR(100) DEFAULT 'CAPEC/NIST',
    PRIMARY KEY (CWE_ID, TECHNIQUE_ID)
);

CREATE TABLE IF NOT EXISTS KB_VULN_STANDARDS (
    DOCUMENT_NAME VARCHAR(200) NOT NULL,
    SECTION_TITLE VARCHAR(500),
    CHUNK_TEXT TEXT,
    CHUNK_INDEX INTEGER,
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
