USE DATABASE SANDBOX;
USE SCHEMA GDUMA;

CREATE OR REPLACE VIEW V_FACT_VULNERABILITY AS
SELECT
    n.CVE_ID,
    n.PUBLISHED_DATE,
    n.LAST_MODIFIED_DATE,
    n.VULN_STATUS,
    n.DESCRIPTION,
    n.CVSS_V31_BASE_SCORE,
    n.CVSS_V31_EXPLOITABILITY_SCORE,
    n.CVSS_V31_IMPACT_SCORE,
    n.CWE_IDS,
    n.CPE_CRITERIA,
    e.EPSS_SCORE,
    e.EPSS_PERCENTILE,
    CASE
        WHEN n.CVSS_V31_BASE_SCORE >= 9.0 THEN 'CRITICAL'
        WHEN n.CVSS_V31_BASE_SCORE >= 7.0 THEN 'HIGH'
        WHEN n.CVSS_V31_BASE_SCORE >= 4.0 THEN 'MEDIUM'
        WHEN n.CVSS_V31_BASE_SCORE >= 0.1 THEN 'LOW'
        ELSE 'NONE'
    END AS SEVERITY_BAND,
    CASE
        WHEN e.EPSS_PERCENTILE >= 0.95 THEN 'VERY HIGH'
        WHEN e.EPSS_PERCENTILE >= 0.80 THEN 'HIGH'
        WHEN e.EPSS_PERCENTILE >= 0.50 THEN 'MEDIUM'
        WHEN e.EPSS_PERCENTILE >= 0.20 THEN 'LOW'
        ELSE 'VERY LOW'
    END AS EPSS_BAND,
    CASE WHEN k.CVE_ID IS NOT NULL THEN TRUE ELSE FALSE END AS IS_KNOWN_EXPLOITED,
    k.VENDOR_PROJECT AS KEV_VENDOR,
    k.PRODUCT AS KEV_PRODUCT,
    k.DATE_ADDED AS KEV_DATE_ADDED,
    k.DUE_DATE AS KEV_DUE_DATE,
    k.KNOWN_RANSOMWARE_CAMPAIGN_USE,
    CASE WHEN k.DUE_DATE < CURRENT_DATE() THEN TRUE ELSE FALSE END AS KEV_REMEDIATION_OVERDUE,
    YEAR(n.PUBLISHED_DATE) AS PUBLISHED_YEAR,
    QUARTER(n.PUBLISHED_DATE) AS PUBLISHED_QUARTER,
    MONTH(n.PUBLISHED_DATE) AS PUBLISHED_MONTH
FROM RAW_NVD_CVES n
LEFT JOIN RAW_EPSS_SCORES e ON n.CVE_ID = e.CVE_ID
LEFT JOIN RAW_CISA_KEV k ON n.CVE_ID = k.CVE_ID;

CREATE OR REPLACE VIEW V_DIM_WEAKNESS AS
SELECT
    CWE_ID,
    NAME AS WEAKNESS_NAME,
    ABSTRACTION,
    STATUS,
    DESCRIPTION
FROM RAW_CWE_WEAKNESSES
WHERE STATUS != 'Deprecated';

CREATE OR REPLACE VIEW V_BRIDGE_CVE_CWE AS
SELECT
    n.CVE_ID,
    TRIM(c.VALUE::STRING) AS CWE_ID
FROM RAW_NVD_CVES n,
    LATERAL SPLIT_TO_TABLE(n.CWE_IDS, ',') c
WHERE n.CWE_IDS IS NOT NULL AND n.CWE_IDS != '';

CREATE OR REPLACE VIEW V_CVE_ATTACK_TACTICS AS
SELECT DISTINCT
    b.CVE_ID,
    m.TECHNIQUE_ID,
    m.TECHNIQUE_NAME,
    m.TACTIC
FROM V_BRIDGE_CVE_CWE b
JOIN MAP_CWE_ATTACK m ON b.CWE_ID = m.CWE_ID;

CREATE OR REPLACE VIEW V_KEV_DETAIL AS
SELECT
    CVE_ID,
    VENDOR_PROJECT,
    PRODUCT,
    VULNERABILITY_NAME,
    DATE_ADDED,
    DUE_DATE,
    REQUIRED_ACTION,
    KNOWN_RANSOMWARE_CAMPAIGN_USE,
    NOTES,
    CASE WHEN DUE_DATE < CURRENT_DATE() THEN TRUE ELSE FALSE END AS IS_OVERDUE,
    DATEDIFF('day', DATE_ADDED, CURRENT_DATE()) AS DAYS_SINCE_ADDED,
    DATEDIFF('day', CURRENT_DATE(), DUE_DATE) AS DAYS_UNTIL_DUE
FROM RAW_CISA_KEV;

CREATE OR REPLACE VIEW V_PHISHING_RELEVANCE AS
SELECT
    t.CVE_ID,
    t.TECHNIQUE_ID,
    t.TECHNIQUE_NAME,
    t.TACTIC,
    CASE
        WHEN t.TECHNIQUE_ID LIKE 'T1566%' OR t.TECHNIQUE_ID LIKE 'T1598%' THEN 'DIRECT_PHISHING'
        WHEN t.TECHNIQUE_ID IN ('T1204.001','T1204.002','T1189') THEN 'PHISHING_ENABLER'
        ELSE 'PHISHING_ENABLER'
    END AS PHISHING_CATEGORY
FROM V_CVE_ATTACK_TACTICS t
WHERE t.TECHNIQUE_ID LIKE 'T1566%'
   OR t.TECHNIQUE_ID LIKE 'T1598%'
   OR t.TECHNIQUE_ID IN ('T1204.001','T1204.002','T1189');
