api:
  image: vuln-mcp-api:latest
  replicas: 2
  port: 8000
  baseUrl: ""
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

frontend:
  image: vuln-mcp-frontend:latest
  replicas: 2
  port: 3000
  baseUrl: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

snowflake:
  account: ""
  user: ""
  role: "ALL_AAI_ARCHITECTS"
  warehouse: "DEFAULT_USER_WH"
  database: "SANDBOX"
  schema: "GDUMA"

github:
  mcpClientId: "Iv23liyRuSENCxUvzaLu"

ingress:
  enabled: false
  host: vuln-mcp.phdata.io
